kreate-community/kreate-web

containers/PageProjectDetails/containers/ModalBackProject/index.tsx, containers/PageProjectDetails/containers/ModalWithdrawFund/index.tsx, containers/PageProjectDetails/containers/PanelProtocolReward/containers/ModalClaimReward/index.tsx, containers/PageProjectDetails/containers/ProjectOverview/containers/ModalCloseProject/index.tsx, containers/PageUpdateProjectV2/containers/ModalSponsorship/index.tsx, containers/PageUpdateProjectV2/containers/ModalUpdateProject/index.tsx
=> fix: USD estimation in modals

containers/PageProjectDetails/containers/ProjectDetails/containers/TabActivities/components/ActivityAction/index.module.scss, containers/PageProjectDetails/containers/ProjectDetails/containers/TabActivities/components/ActivityAction/index.tsx
https://user-images.githubusercontent.com/110230002/222081926-91304a34-ff56-4948-8f06-9343576acf71.mov
=> feat: update activities panel design

containers/PageHome/containers/ProjectCarousel/components/ProjectCard/index.module.scss
https://app.asana.com/0/1203842063837585/1204085713144049
=> fix: display position of matching project properly

pages/index.tsx
Resolves: https://app.asana.com/0/0/1204062700178987/f
=> feat: fallback data for pagehome regular projects

modules/next-backend/logic/getAllActivities.ts, modules/next-backend/logic/getAllAnnouncementsByProjectId.ts, modules/next-backend/logic/getAllProjectMilestoneSnapshots.ts, modules/next-backend/logic/getAllProjects.ts, modules/next-backend/logic/getBackedProjectsByBacker.ts, modules/next-backend/logic/getDetailedProject.ts, modules/next-backend/logic/getProjectMatch.ts, modules/next-backend/logic/getProtocolStatistics.ts, modules/next-backend/logic/getTotalStakedByBacker.ts
https://app.asana.com/0/1203842063837585/1204060442247904
=> fix: don't query blocked projects

containers/PageEditProject/containers/ModalGroup$CreateProject/components/ModalSubmit/index.tsx, containers/PageEditProject/containers/ModalGroup$CreateProject/components/ModalSuccess/index.tsx, containers/PageProjectDetails/containers/ModalBackProject/index.tsx, containers/PageProjectDetails/containers/PanelAdjustStake/containers/ModalUnbackProject/index.tsx, containers/PageProjectDetails/containers/PanelProtocolReward/utils/submitClaimTeikiTx.ts, containers/PageProjectDetails/containers/ProjectOverview/containers/ModalCloseProject/index.tsx, containers/PageUpdateProjectV2/containers/ModalPostAnnouncement/index.tsx, containers/PageUpdateProjectV2/containers/ModalUpdateProject/index.tsx
Partially resolves https://app.asana.com/0/1203842063837585/1204061704885990
=> refactor: provide more details when throwing errors

containers/PageHome/containers/NavBar/index.tsx, containers/PageProjectDetails/hooks/useDetailedProject.ts, containers/PageProjectDetails/index.tsx, pages/projects-by-id/[projectId]/index.tsx, pages/projects/[projectCustomUrl]/index.tsx
Related to https://app.asana.com/0/1203842063837585/1204110849059470/f
This PR resolves one TODO comment from https://github.com/teiki-network/teiki-web/pull/18/files
=> Display page 404 if project is not found

containers/PagePreviewProject/index.tsx, containers/PageProfile/containers/PanelBackingProjects/index.tsx, containers/PageProjectDetails/containers/ModalBackProject/index.tsx, containers/PageProjectDetails/index.tsx, modules/teiki-components/components/PanelProjectOverview/containers/ButtonGroup/index.tsx, modules/teiki-components/components/PanelProjectOverview/types.ts, pages/secret-playground/demo-project-overview.tsx
We show "Stake more" for existing members and "Become a Member" for unsubscribed users.
=> fix: copywriting for existing members

modules/modal-promises/index.tsx, modules/teiki-ui/components/Modal/components/Container/index.module.scss, modules/teiki-ui/components/Modal/components/Container/index.tsx
Resolves https://app.asana.com/0/1203842063837585/1203982387389794
https://user-images.githubusercontent.com/117076162/223407753-7556884b-30af-4039-afea-619ded13ad40.mp4
=> fix: display overlayed modals properly

containers/PageUpdateProjectV2/containers/ModalSponsorship/index.tsx, containers/PageUpdateProjectV2/containers/ModalUpdateProject/index.tsx
https://user-images.githubusercontent.com/110230002/223618113-ff284f65-f6d2-4db3-937b-9a9e5131a5ca.mov
Resolves: https://app.asana.com/0/0/1203982387389794/1204133587487268/f
=> fix: refine modal update

containers/PageHome/containers/NavBar/index.tsx, containers/PageProjectDetails/index.tsx
https://app.asana.com/0/home/1203849283056222/1204131242029312
=> fix: wallet randomly disconnects

containers/PageHome/containers/PanelProtocolStatistics/index.tsx, modules/business-types/index.ts, modules/data-faker/index.ts, modules/next-backend/logic/getProtocolStatistics.ts
https://app.asana.com/0/1203842063837585/1204124790686694
=> feat: add number of posts in protocol statistics

containers/PageHome/containers/NavBar/index.module.scss, containers/PageHome/containers/ProjectCarousel/index.module.scss, containers/PageHome/containers/ProjectList/index.module.scss, containers/PageHome/containers/ProjectList/index.tsx, containers/PageHome/containers/SectionSlogan/index.module.scss, containers/PageHome/containers/SectionSlogan/index.tsx, containers/PageHome/index.module.scss, containers/PageHome/index.tsx
=> feat: tweak UI a bit to match the Figma design

containers/PageHome/containers/NavBar/index.module.scss, containers/PageHome/containers/ProjectCarousel/index.module.scss, containers/PageHome/containers/ProjectList/index.module.scss, containers/PageHome/containers/ProjectList/index.tsx, containers/PageHome/containers/SectionSlogan/index.module.scss, containers/PageHome/containers/SectionSlogan/index.tsx, containers/PageHome/index.module.scss, containers/PageHome/index.tsx
Reverts teiki-network/teiki-web#41.
The design still needed to be finalized. Changes to the tagline weren't and won't be approved.
THIS IS A MASSIVE REGRESSION.
=> Revert "feat: tweak UI a bit to match the Figma design"

containers/PageHome/containers/NavBar/containers/ButtonWalletNavbar/containers/ModalConnectWallet/index.module.scss, containers/PageHome/containers/NavBar/containers/ButtonWalletNavbar/containers/ModalConnectWallet/index.tsx
https://app.asana.com/0/home/1203849283056222/1204124790686700
=> feat: Yell Preview Network in the Connect Wallet Modal

modules/teiki-components/components/PanelProjectOverview/containers/TitleSloganViewer/index.module.scss, modules/teiki-components/components/PanelProjectOverview/containers/TitleSloganViewer/index.tsx, modules/teiki-ui/components/Typography/index.module.scss, modules/teiki-ui/components/Typography/index.tsx
Resolves https://app.asana.com/0/1203842063837585/1204126620168021
https://user-images.githubusercontent.com/117076162/223915862-205e1b6d-0498-4172-982c-4a757b8c5922.mp4
=> Add Typography.H1 to Typography.H6

pages/robots.txt.ts, pages/sitemap.txt.ts
Resolves https://app.asana.com/0/1203842063837585/1204126620168014
=> feat: add sitemap.txt and robots.txt

containers/PageHome/containers/PanelProtocolStatistics/index.tsx, modules/business-types/index.ts, modules/data-faker/index.ts, modules/next-backend/logic/getProtocolStatistics.ts
https://app.asana.com/0/1203842063837585/1204160509191235
Tested on:
=> feat: display number of protocol transactions

config/client.ts, config/server.ts, modules/env/client.ts, modules/env/server.ts, modules/env/types.ts, modules/env/utils/parsers.ts, modules/env/utils/wrappers.ts
Resolves https://app.asana.com/0/1203842063837585/1204135105601889
**To do list**
=> feat: add modules/env

modules/teiki-components/components/TableTopBackers/index.tsx
https://app.asana.com/0/1203842063837585/1204133714760783
=> fix: typo: backers -> members

containers/PageHome/containers/ProjectCarousel/components/ProjectCard/index.module.scss, containers/PageHome/containers/ProjectCarousel/components/ProjectCard/index.tsx
https://app.asana.com/0/1203842063837585/1204133675855752
=> fix: x% match labels do not align with project titles in sponsor cards

containers/PageHome/containers/NavBar/containers/ButtonWalletNavbar/containers/ModalConnectWallet/index.tsx
=> fix: disable nufi

containers/PageUpdateProjectV2/containers/ModalUpdateProject/index.tsx, containers/PageUpdateProjectV2/containers/ModalUpdateProject/utils.ts
Resolves: https://app.asana.com/0/1203842063837585/1204036310856827/f
=> fix: update sponsorship expiry information

modules/business-types/index.ts
Resolves: https://app.asana.com/0/1203842063837585/1204000357935813/f
=> fix: project update activity message

containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionProjectCreation.tsx, containers/PageProfile/containers/PanelActivities/components/ActivityViewer/index.tsx, containers/PageProjectDetails/containers/ProjectDetails/containers/TabActivities/components/ActivityAction/index.tsx, modules/business-types/index.ts, modules/next-backend/logic/getAllActivities.ts, modules/next-backend/logic/getDetailedProject.ts, modules/next-backend/logic/getProjectCreation.ts, modules/next-backend/logic/getProjectCreationActivity.ts
Resolve https://app.asana.com/0/1203842063837585/1204097242463663/f
In page details
In profile page:
=> feat: project creation activity

containers/PageUpdateProjectV2/containers/ModalPostAnnouncement/index.module.scss, containers/PageUpdateProjectV2/containers/ModalPostAnnouncement/index.tsx, modules/teiki-ui/components/RadioButton/icons/IconActive.tsx, modules/teiki-ui/components/RadioButton/index.module.scss, modules/teiki-ui/components/RadioButton/index.tsx
https://user-images.githubusercontent.com/110230002/224815769-14a12cf8-45c2-49ed-a2c3-a47a4c8466cb.mov
=> feat: exclusive post UI

containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBanner/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBanner/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBenefit/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBenefit/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/icons/IconDrag.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/icons/IconImage.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/icons/IconTrash.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierPreview/icons/IconEllipse.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierPreview/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierPreview/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/hooks/useField.ts, containers/PageEditProject/containers/ProjectBenefitsEditor/icons/IconPlusSquare.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/index.tsx, containers/PageEditProject/containers/ProjectEditor/index.tsx, containers/PageEditProject/utils.ts, containers/PagePreviewProject/index.tsx, containers/PageProjectDetails/containers/ProjectDetails/index.tsx, containers/PageProjectDetails/index.tsx, containers/PageUpdateProjectV2/utils/storage.ts, modules/business-types/index.ts, modules/next-backend/logic/getDetailedProject.ts, modules/with-bufs-as-converters/converters/project.ts
https://user-images.githubusercontent.com/110230002/225499641-56953ed6-9106-4cf2-a36c-fd4ffbf1cf17.mp4
=> feat: exclusive tiers, create project flow

.env.mainnet, .env.testnet, middleware.ts, modules/env/client.ts, modules/teiki-components/components/ImageView/index.tsx, next.config.js
- Next.js Image Optimization
- Internal IPFS routing
- Content Security Policy
=> feat: prepare for kreate

modules/common-utils/index.ts, modules/next-backend/api/errors.ts, modules/next-backend/logic/postIpfsPin.ts, pages/api/v1/exclusive/decrypt/ipfs/[cid].ts, pages/api/v1/exclusive/encrypt/index.ts, pages/api/v1/exclusive/encrypt/ipfs.ts, pages/api/v1/ipfs/add.ts
And I fixed the file upload limit too.
=> feat: seekable encrypted video

containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBanner/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/components/TierBenefit/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/icons/IconTrash.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierPreview/index.module.scss, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierPreview/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/hooks/useField.ts, containers/PageEditProject/containers/ProjectBenefitsEditor/index.tsx, containers/PageEditProject/containers/ProjectCommunityEditor/ProjectFAQEditor/components/Accordion/icons/IconArrowDropDown.tsx, containers/PageEditProject/containers/ProjectEditor/utils/project-progress.ts, containers/PageProjectDetails/containers/ProjectDetails/index.tsx, modules/business-types/index.ts, modules/teiki-components/components/Resizable/index.tsx, modules/teiki-components/components/RichTextEditor/index.tsx, modules/teiki-components/components/RichTextViewer/index.module.scss, modules/teiki-components/components/RichTextViewer/index.tsx, modules/with-bufs-as-converters/converters/project.ts
https://user-images.githubusercontent.com/110230002/225876668-8c66c89a-00d2-4ecd-b1f0-d0a755d4ce1a.mov
=> feat: re-skin exclusive tiers in create project

modules/ada-handle/utils.ts, modules/next-backend-client/api/httpGetAdaHandle.ts, modules/teiki-ui/components/InlineAddress/index.tsx
https://app.asana.com/0/1203842063837585/1204124790686697
=> feat: integrate ada handle

containers/PageProjectDetails/containers/ModalBackProject/utils/transaction.ts, containers/PageProjectDetails/containers/PanelAdjustStake/containers/ModalUnbackProject/utils/transaction.ts
https://app.asana.com/0/1203842063837585/1204053223987089
=> fix: don't attach metadata when message is empty

containers/PageUpdateProjectV2/containers/ModalPostAnnouncement/index.tsx, modules/teiki-ui/components/RadioButton/index.module.scss
=> feat: update post modal to design

containers/PageProjectDetails/containers/ProjectDetails/containers/TabUpdates/components/CommunityUpdateDetails/index.tsx
=> feat: use RichTextViewer for posts

containers/PageProjectDetails/containers/ModalBackProject/index.tsx, containers/PageProjectDetails/containers/PanelProjectStatistics/index.module.scss, containers/PageProjectDetails/containers/PanelProjectStatistics/index.tsx, containers/PageProjectDetails/index.tsx
https://app.asana.com/0/1203842063837585/1204212765783447
=> feat: panel project statistics

containers/PagePreviewProject/index.tsx, containers/PageProjectDetails/containers/PanelProjectStatistics/index.tsx, containers/PageProjectDetails/index.tsx, modules/teiki-components/components/LogoImageViewer/index.module.scss, modules/teiki-components/components/LogoImageViewer/index.tsx, modules/teiki-components/components/PanelProjectOverview/containers/HistoryViewerV2/index.tsx, modules/teiki-components/components/PanelProjectOverview/containers/TagsViewer/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/BannerCarousel/index.module.scss, modules/teiki-components/components/PanelProjectOverviewV2/components/BannerCarousel/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Section/index.module.scss, modules/teiki-components/components/PanelProjectOverviewV2/components/Section/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconClose.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconEditPencil.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconEditPencilLine.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconLeaf.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconShare.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/icons/IconThreeDots.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/index.module.scss, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/index.module.scss, modules/teiki-components/components/PanelProjectOverviewV2/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/types.ts, modules/teiki-ui/components/DropdownMenu/components/Item/index.tsx, modules/teiki-ui/components/DropdownMenu/components/Menu/index.module.scss
Blocked by:
Resolves https://app.asana.com/0/1203842063837585/1204212765783447
Uploading Screen Recording 2023-03-21 at 14.01.55.mov.mp4…
=> Replace PanelProjectOverview by PanelProjectOverviewV2

containers/PageProjectDetails/index.tsx, modules/business-types/index.ts, modules/next-backend/logic/getAllPostsByProjectId.ts
~~Làm Haskell bao nhiêu năm rồi mà vẫn thiết kế type như này...~~
=> fix: counting exclusive posts

modules/with-bufs-as-converters/codecs/CodecBlob.ts, modules/with-bufs-as-converters/utils/buffer.ts
https://app.asana.com/0/home/1203849283056222/1204115146622395
=> feat: implement blobToSha256

containers/PageKolours/containers/PanelMintKolours/components/PaletteCell/index.tsx, containers/PageKolours/containers/PanelMintKolours/index.tsx
=> feat: allow selection and add mint button

containers/PageKolours/containers/NftCard/components/CompleteIndicator/index.module.scss, containers/PageKolours/containers/NftCard/components/CompleteIndicator/index.tsx, containers/PageKolours/containers/NftCard/components/PaletteBar/index.module.scss, containers/PageKolours/containers/NftCard/components/PaletteBar/index.tsx, containers/PageKolours/containers/NftCard/index.module.scss, containers/PageKolours/containers/NftCard/index.tsx, containers/PageKolours/containers/NftCardGrid/index.module.scss, containers/PageKolours/containers/NftCardGrid/index.tsx
https://user-images.githubusercontent.com/110230002/227104015-ba415826-9a19-4f25-948c-4c551a3141f9.mp4
Resolves: https://app.asana.com/0/0/1204231410171179/f
=> feat: improve NftCardGrid

modules/kolours/common.ts, modules/kolours/genesis-kreation.ts, pages/api/kolours/genesis-kreation/quote.ts, pages/api/kolours/genesis-kreation/submit.ts, pages/api/kolours/kolour/quote.ts, pages/api/kolours/kolour/submit.ts
=> feat: genesis-kreation quote & submit

containers/PageKolours/containers/PanelMint/components/NftPrice/index.module.scss, containers/PageKolours/containers/PanelMint/components/NftPrice/index.tsx, containers/PageKolours/containers/PanelMint/components/NftPrice/utils.ts, containers/PageKolours/containers/PanelMint/components/Viewer/index.module.scss, containers/PageKolours/containers/PanelMint/components/Viewer/index.tsx, containers/PageKolours/containers/PanelMint/index.tsx, containers/PageKolours/index.tsx, containers/PageKolours/kolours-types.ts, containers/PageKolours/mock/httpGetAllNfts.ts
=> feat: display nft fee

modules/kolours/genesis-kreation.ts, modules/next-backend/utils/CodecCid.ts, modules/urls/index.ts, pages/api/kolours/genesis-kreation/list.ts, pages/api/kolours/genesis-kreation/quote.ts
=> feat: /genesis-kreation/list

containers/PageKolours/containers/PanelMint/components/NftPrice/index.module.scss, containers/PageKolours/containers/PanelMint/components/Palette/index.module.scss, containers/PageKolours/containers/PanelMint/components/Palette/index.tsx, containers/PageKolours/containers/PanelMint/components/PaletteCell/index.tsx, containers/PageKolours/containers/PanelMint/components/Viewer/index.module.scss, containers/PageKolours/containers/PanelMint/components/Viewer/index.tsx, containers/PageKolours/containers/PanelMint/index.module.scss, containers/PageKolours/containers/PanelMint/index.tsx, containers/PageKolours/index.tsx
=> style: adjust style to match the design

containers/PageKolours/api/httpGetAllNfts.ts, containers/PageKolours/hooks/useAllNfts.ts, containers/PageKolours/mock/httpGetAllNfts.ts
https://user-images.githubusercontent.com/117076162/227284647-5cc5c620-9624-4f0c-a7df-bd0fb2ae57c3.mp4
=> feat: implement httpGetAllNfts

containers/PageKolours/containers/PanelMint/components/Checkbox/index.module.scss, containers/PageKolours/containers/PanelMint/components/Checkbox/index.tsx, containers/PageKolours/containers/PanelMint/components/NftPrice/index.tsx, containers/PageKolours/containers/PanelMint/components/PaletteCell/index.tsx
https://user-images.githubusercontent.com/117076162/227300456-b15d5d87-6087-4225-a93c-95f05934cdd8.mp4
=> feat: implement Checkbox properly

containers/PageKolours/containers/BelowNavBar/index.module.scss, containers/PageKolours/containers/BelowNavBar/index.tsx, containers/PageKolours/index.tsx, modules/teiki-ui/components/Typography/index.module.scss, modules/teiki-ui/components/Typography/index.tsx
https://user-images.githubusercontent.com/117076162/227313351-79adb27b-a914-45bc-ba16-e64cc83768c1.mp4
=> feat: add BelowNavBar

containers/PageKolours/components/Section/index.tsx, containers/PageKolours/containers/NftCard/index.module.scss, containers/PageKolours/containers/PanelMint/components/Viewer/index.tsx, containers/PageKolours/containers/PanelMint/index.tsx, containers/PageKolours/index.tsx
https://user-images.githubusercontent.com/117076162/227320000-d56539e1-a0ed-46ac-8c6c-cc1a7655dca2.mp4
=> feat: show final image if everything is checked; feat: scroll to top when selecting a nft

modules/teiki-ui/components/RadioGroup$AsButton/index.module.scss, modules/teiki-ui/components/RadioGroup$AsButton/index.tsx, package-lock.json, package.json
The icon and label order is reverted. The screencast is a bit outdated
https://user-images.githubusercontent.com/128346242/227466721-78689104-8bb9-4bc7-8985-78dc4b6840dd.mp4
Resolves: https://app.asana.com/0/0/1204231410171192/f
=> feat: add RadioGroup

modules/kolours/common.ts, modules/kolours/fees.ts, modules/kolours/genesis-kreation.ts, modules/kolours/kolour.ts, modules/kolours/types/Kolours.ts, modules/next-backend/locking.ts, pages/api/kolours/genesis-kreation/list.ts, pages/api/kolours/genesis-kreation/quote.ts, pages/api/kolours/kolour/quote.ts
=> feat: kolours pool referral

containers/PageKolours/containers/PanelMint/components/PaletteCell/index.tsx, modules/teiki-ui/components/AssetViewer/components/Ada$ZeroFractionDigits.tsx, modules/teiki-ui/components/AssetViewer/index.tsx
=> fix: do not display kolour precision

containers/PageHome/components/ProjectTagList/index.tsx
Resolves: https://app.asana.com/0/1203842063837585/1204223774581484/f
=> feat: change project tag from anchor to span

containers/PageKoloursGallery/api/httpGetAllMintedKolours.ts, containers/PageKoloursGallery/components/Section/index.module.scss, containers/PageKoloursGallery/components/Section/index.tsx, containers/PageKoloursGallery/containers/GenesisNftCard/index.module.scss, containers/PageKoloursGallery/containers/GenesisNftCard/index.tsx, containers/PageKoloursGallery/containers/GenesisNftList/index.module.scss, containers/PageKoloursGallery/containers/GenesisNftList/index.tsx, containers/PageKoloursGallery/containers/KolourCard/index.module.scss, containers/PageKoloursGallery/containers/KolourCard/index.tsx, containers/PageKoloursGallery/containers/KolourList/index.module.scss, containers/PageKoloursGallery/containers/KolourList/index.tsx, containers/PageKoloursGallery/hooks/useAllMintedKolours.ts, containers/PageKoloursGallery/index.module.scss, containers/PageKoloursGallery/index.tsx, modules/kolours/kolour.ts, modules/kolours/types/Kolours.ts, pages/api/kolours/kolour/list-minted.ts, pages/kolours/gallery/all.tsx
https://user-images.githubusercontent.com/117076162/227602282-715a5a19-3187-4b0e-86a9-15c65b24ec26.mp4
=> Add Gallery page

containers/LandingPage/components/IconViewGallery/index.tsx, containers/LandingPage/containers/NftCollection/index.tsx, containers/LandingPage/index.module.scss, containers/LandingPage/index.tsx
[Screencast from 25-03-2023 14:44:36.webm](https://user-images.githubusercontent.com/110231356/227704612-77ec5c43-b67a-4395-9205-87ed896cc887.webm)
=> fix: refine landing page

containers/PageHome/containers/ProjectCarousel/components/ProjectCard/index.tsx
https://app.asana.com/0/1203842063837585/1204076571649913/f
=> fix: sponsor kreators stats layout

package-lock.json, package.json, pages/api/kolours/genesis-kreation/quote.ts, pages/api/kolours/genesis-kreation/submit.ts, pages/api/kolours/kolour/quote.ts
- add required stake credential signatures to kolours txs
- properly handle expiration time
=> feat: require stake credential signature with referral

containers/PageKolours/containers/PanelMint/components/Viewer/index.tsx, containers/PageKolours/containers/PanelMint/index.tsx
=> refine: indicate minted genesis NFTs at carousel

containers/PageKolours/containers/NftCard/index.tsx, containers/PageKolours/mock/httpGetAllNfts.ts, containers/PageKoloursGallery/containers/GenesisNftCard/index.tsx, containers/PageKoloursGallery/containers/KolourCard/index.tsx, containers/PageKoloursGallery/containers/SwitchTab/index.module.scss, containers/PageKoloursGallery/containers/SwitchTab/index.tsx, containers/PageKoloursGallery/index.tsx, modules/kolours/genesis-kreation.ts, modules/kolours/kolour.ts, modules/kolours/types/Kolours.ts
[Screencast from 27-03-2023 18:16:50.webm](https://user-images.githubusercontent.com/110231356/227926853-527c5e5f-08d7-4435-ba1c-1b654a156611.webm)
=> feat: more information in gallery page

containers/PageKolours/containers/NavBar/index.module.scss, containers/PageKolours/containers/NavBar/index.tsx
Before:
After:
https://user-images.githubusercontent.com/128346242/228133660-eba9ee88-2bd6-466a-b485-f063319d4c51.mp4
=> style: hide discount advert if screen size is smaller than 1024px

containers/PageKolours/containers/ModalMintKoloursSuccess/containers/SocialMedia/index.module.scss, containers/PageKolours/containers/ModalMintKoloursSuccess/containers/SocialMedia/index.tsx
https://user-images.githubusercontent.com/110230002/228123690-9e747ab3-7372-472d-a3d2-f79f40404b42.mov
=> fix: modal minting nft success share buttons

containers/PageHome/containers/ProjectCarousel/components/ProjectCard/index.tsx, containers/PageHome/containers/ProjectList/components/ProjectListItem/index.tsx
https://user-images.githubusercontent.com/110230002/228128551-db581df3-04c2-4555-a07f-e1db6f5fa3e4.mp4
https://app.asana.com/0/1203842063837585/1204267832406186/f
=> feat: hides kreator stats

containers/PageProjectDetails/index.tsx
https://app.asana.com/0/1203842063837585/1204265141331487/f
=> feat: hide teiki claiming section

containers/LandingPage/containers/RewardsSection/index.tsx, containers/PageEditProject/containers/ProjectBasicsEditor/containers/BasicForm/components/InputTagsWithSuggestions/index.tsx, containers/PageEditProject/containers/ProjectBenefitsEditor/components/TierInput/index.tsx, containers/PageHome/components/ProjectStats/index.tsx, containers/PageHome/containers/PanelProtocolStatistics/index.tsx, containers/PageHome/index.tsx, containers/PageProjectDetails/containers/ModalBackProject/index.tsx, containers/PageProjectDetails/containers/PanelBenefits/containers/TierViewer/containers/Tier/index.tsx, containers/PageProjectDetails/containers/PanelProjectStatistics/index.tsx, containers/PageProjectDetails/containers/PanelTopBackers/index.tsx, containers/PageProjectDetails/containers/ProjectDetails/containers/TabUpdates/components/CommunityUpdateOverview/index.tsx, containers/PageUpdateProjectV2/containers/ModalUpdateProject/index.tsx, modules/next-backend/logic/getDetailedProject.ts, modules/teiki-components/components/PanelProjectOverview/containers/ButtonGroup/index.tsx, modules/teiki-components/components/PanelProjectOverview/containers/OtherStatsViewer/index.tsx, modules/teiki-components/components/PanelProjectOverviewV2/components/Toolbar/index.tsx, modules/teiki-components/components/TableTopBackers/index.tsx, modules/teiki-components/components/TeikiHead/index.tsx
"Member"s in meta tags have not been changed.
https://app.asana.com/0/1203842063837585/1204267832406183/f
=> feat: copywriting, change member to fan

containers/LandingPage/containers/KreataverseStory/components/LeftStory/index.module.scss, containers/LandingPage/containers/KreataverseStory/components/LeftStory/index.tsx, containers/LandingPage/containers/KreataverseStory/components/RightStory/index.module.scss, containers/LandingPage/containers/KreataverseStory/components/RightStory/index.tsx, containers/LandingPage/containers/KreataverseStory/index.module.scss, containers/LandingPage/containers/KreataverseStory/index.tsx, containers/LandingPage/index.tsx
https://user-images.githubusercontent.com/110230667/228155339-752aeda4-4374-4f78-b89d-3c73bbe20873.mov
=> feat: re-design kreataverse story at landing page

containers/LandingPage/containers/KreataverseStory/index.module.scss, containers/LandingPage/containers/KreataverseStory/index.tsx
@tori-kreate  sorry for letting you down...
=> fix: better responsive for kreataverse story

containers/PageKolourDetails/components/Section/index.module.scss, containers/PageKolourDetails/components/Section/index.tsx, containers/PageKolourDetails/hooks/useMintedKolour.ts, containers/PageKolourDetails/icons/IconCrown.tsx, containers/PageKolourDetails/icons/IconSeparator.tsx, containers/PageKolourDetails/index.module.scss, containers/PageKolourDetails/index.tsx, modules/kolours/types/Kolours.ts, pages/kolours/kolour/[kolour]/index.tsx
=> feat: initialize PageKolourDetails

modules/teiki-ui/components/ColorPicker/index.module.scss, modules/teiki-ui/components/ColorPicker/index.tsx, modules/teiki-ui/components/ColorPicker/utils.ts, package-lock.json, package.json
Heads up: this pull install new dependency [react-colorful](https://www.npmjs.com/package/react-colorful)
Resolves: https://app.asana.com/0/1203842063837585/1204287576890309/f
https://user-images.githubusercontent.com/128346242/228522392-d68d6ec1-605a-43c7-9967-1e6e7d9925b6.mp4
=> feat: add ColorPicker component

containers/PageKolours/utils.ts, containers/PageMintByColorPicker/components/Section/index.module.scss, containers/PageMintByColorPicker/components/Section/index.tsx, containers/PageMintByColorPicker/containers/PanelPickedKolours/index.module.scss, containers/PageMintByColorPicker/containers/PanelPickedKolours/index.tsx, containers/PageMintByColorPicker/index.module.scss, containers/PageMintByColorPicker/index.tsx, pages/kolours/mint-by-color-picker/index.tsx
Partially resolves https://app.asana.com/0/1203842063837585/1204278354437788
Understanding that the feature is not complete, I added this piece of code.
```
if (!SHOW_SECRET_ROUTES) {
return { notFound: true };
}
```
Please merge this PR so that other devs can join the development.
https://user-images.githubusercontent.com/117076162/228806094-f65a9156-f50d-4fb9-b11a-0dca67f1348c.mp4
=> feat: add PageMintByColorPicker

containers/PageMintByColorPicker/containers/PanelPickedKolours/hooks/useFreeKolour.ts, containers/PageMintByColorPicker/containers/PanelPickedKolours/index.tsx, modules/next-backend-client/api/httpGetFreeKolour.ts, pages/api/kolours/kolour/free.ts
=> fix: hardcoded free kolour quota

containers/PageKoloursGallery/containers/KolourCard/index.tsx
Resolves: https://app.asana.com/0/0/1204296603625127/f
=> feat: entrypoint to kolour page

containers/PageMintByColorPicker/containers/PanelPickedKolours/index.module.scss, containers/PageMintByColorPicker/containers/PanelPickedKolours/index.tsx, containers/PageMintByColorPicker/icons/IconGift.tsx, containers/PageMintByColorPicker/index.tsx
#274 and #277 must be merged first
https://user-images.githubusercontent.com/110230002/228907481-bed70620-2351-4675-8712-5ed4b7ee49b0.mp4
Resolves: https://app.asana.com/0/0/1204298850649585/f
=> fix: invalid free kolour mint meaningful error & disable controls

containers/PageMintByColorPicker/containers/PanelPickedKolours/index.tsx
https://user-images.githubusercontent.com/110230667/229033048-96979fb5-140c-4b5e-9ebf-7d51cf064a2e.mov
=> feat: subtotal in free kolours page

containers/PageMintByColorPicker/containers/PanelPickedKolours/index.module.scss, containers/PageMintByColorPicker/containers/PanelPickedKolours/index.tsx, containers/PageMintByColorPicker/icons/IconAdd.tsx, containers/PageMintByColorPicker/index.tsx
https://user-images.githubusercontent.com/117076162/229068593-612f0f4a-c3df-4f74-8e22-62eebd46be97.mp4
=> feat: move button Add to Collection to the correct place

containers/PageKolourDetails/api/httpGetMintedKolour.ts, containers/PageKolourDetails/hooks/useMintedKolour.ts, modules/kolours/kolour.ts, pages/api/kolours/kolour/list/minted.ts, pages/api/kolours/kolour/minted/detail.ts
resolves: https://app.asana.com/0/0/1204296603625125/f
=> fix: properly implement useMintedKolour

containers/PageKolourDetails/index.tsx, containers/PageKoloursGallery/containers/KolourCard/index.tsx, modules/kolours/kolour.ts, modules/kolours/types/Kolours.ts
Resolve: https://app.asana.com/0/0/1204296603625121/f
=> feat: add minted time for kolour details page

containers/PageKolourDetails/index.module.scss, containers/PageKolourDetails/index.tsx
=> feat: update page kolour nft detail

containers/PageKolours/containers/NavBar/index.tsx, containers/PageKolours/index.tsx, containers/PageMintByColorPicker/index.tsx
=> fix: copywriting

containers/PageKolours/containers/ModalFreeMintKolour/index.tsx, containers/PageKolours/containers/ModalFreeMintKolour/utils/transaction.ts, containers/PageKolours/containers/ModalMintGenesisKreation/hooks/useEstimatedFees.ts, containers/PageKolours/containers/ModalMintGenesisKreation/utils/transaction.ts, containers/PageKolours/containers/ModalMintKolour/hooks/useEstimatedFees.ts, containers/PageKolours/containers/ModalMintKolour/index.tsx, containers/PageKolours/containers/ModalMintKolour/utils/transaction.ts, containers/PageKolours/containers/PanelMint/index.tsx, containers/PageMintFree/containers/PanelPickedKolours/index.tsx, modules/kolours/types/Kolours.ts, modules/next-backend-client/api/httpGetQuoteGKNft.ts, modules/next-backend-client/api/httpPostMintGKNftTx.ts, modules/next-backend-client/api/httpPostMintKolourNftTx.ts, package-lock.json, package.json, pages/api/kolours/genesis-kreation/quote.ts, pages/api/kolours/genesis-kreation/submit.ts, pages/api/kolours/kolour/quote.ts, pages/api/kolours/kolour/submit.ts
=> fix: fee estimation in genesis & kolour mint

containers/PageKolours/containers/ModalMintGenesisKreation/utils/transaction.ts, containers/PageKoloursGallery/containers/GenesisNftCard/index.tsx, containers/PageKoloursGalleryDetails/index.module.scss, containers/PageKoloursGalleryDetails/index.tsx, modules/array-utils/index.ts
=> feat: more lengthy genesis description

containers/PageHome/containers/NavBar/index.module.scss, containers/PageHome/containers/NavBar/index.tsx, containers/PageHome/index.tsx
=> feat: add closing ribbon
